trigger:
- develop

pool:
  vmImage: 'windows-latest'  # Change to use a Windows agent pool

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli@12
    npm install --legacy-peer-deps
    
  displayName: 'Install Angular CLI and dependencies'

- script: |
    npm run build:ssr

  displayName: 'Build Angular app'



- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
  displayName: 'Archive build artifacts'

- task: AzureRmWebAppDeployment@4
  inputs:
    azureSubscription: 'AzureRm'  # Azure subscription service connection
    appType: 'webApp'
    WebAppName: 'webapp-modher-frontend-web'  # Azure App Service name
    package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'  
